### ISSUE TITLE
Just some question and suggestions, not bug

### ISSUE THREAD

**Issue by CsloudX** [DigvijaysinhGohil/Godot-Shader-Lib#6]
suggestions:
1. add version to addons/shaderlib. for me, i'm not sure my shaderlib plugin was the latest because i don't know shaderlib's version for my project. or add a auto update feature, dialogue_manager & phantom_camera has this feature.
2. add some demo scene, so love this plugin. but for beginner like me. some nodes I don't know how to or which situation should use.

questions:
1. why verstion 1.2.2->2.2.2? not 1.2.2->1.2.3 or 1->1.3.0 or 2.0.0?

**Comment by DigvijaysinhGohil** [comment]
I will definitely consider your suggestions moving forward.

As far as the versioning goes, I am following something like MajorOverhaul.NewNodeImplementation.MinorBugFixes.
e.g. I have gone 1.2.0 to 2.0.0 because I rewrite most of the things to support Godot 4.2.

That's why in the release section there are only two release packages 2.x.x which supports Godot 4.2 and 1.x.x which supports Godot 4.1. 

Previous minor releases are not available because let's say in 2.2.3 you will have everything you had in 2.0.0. In addition you will have new nodes and latest bug fixes.
